name = "twr-donation-ticker"
main = "src/index.js"
compatibility_date = "2026-06-16"

[[d1_databases]]
binding = "DONATIONS_DB"
database_name = "twr-donations"
database_id = "44491b2a-9395-4e4e-9c45-903579b1a2f5"
